version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: vessel-db
    environment:
      - POSTGRES_USER=adminroot
      - POSTGRES_PASSWORD=vesseldb12345
      - POSTGRES_DB=vessel
    ports:
      - "5432:5432"
